//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.

/*
Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

//var s = "abcd"
//var t = "abcde"

var s = "a"
var t = "aa"

func findTheDifference(_ s: String, _ t: String) -> Character {
    
    var tmpResult = Array(t)
    
    for (_, value) in s.enumerated() {
        let tmpIndex = tmpResult.lastIndex(of: value)
        tmpResult.remove(at: tmpIndex!)
    }
    return tmpResult.last!
}

findTheDifference(s, t)
